### ISSUE TITLE
Скрытие постов не работает

### ISSUE THREAD

**Issue by UserNaem** [VVatashi/TinyIB#1]
STR:
1. Установить dE
2. Ткнуть "скрыть" рядом с любым постом
Ожидания:
Пост скроется.
Реальность:
dE считает пост скрытым, но его внешний вид не меняется.

**Comment by VVatashi** [comment]
Проблема dE.

**Comment by VVatashi** [comment]
Было исправлено в какой-то момент. ¯\_(ツ)_/¯
