### ISSUE TITLE
Respect jpeg rotation information

### ISSUE THREAD

**Issue by UserNaem** [VVatashi/TinyIB#65]
https://lewd.ga/b/res/4405#q4428
Affects both "in post" and "in popup" file view options, but not the thumbnail

**Comment by VVatashi** [comment]
Превью изображения поворачивается с учётом информации о повороте.
Оригинал никак не обрабатывается, и я не планирую его обрабатывать. То, что его информация о повороте может не учитываться браузером - скорее проблема браузера.

**Comment by UserNaem** [comment]
Все браузеры уважают поворот при открытии файла в новой вкладке, так что баг не в браузере

**Comment by VVatashi** [comment]
> Все браузеры уважают поворот при открытии файла в новой вкладке, так что баг не в браузере

Firefox для этого добавляет к изображению свойство `image-orientation: from-image;`, которое только в нём и поддерживается. (См. https://caniuse.com/#search=image-orientation)
Chromium-based браузеры, на сколько я знаю, учитывают EXIF только при выводе в новой вкладке - это хак, и не существует никакого способа сделать это в HTML. (См. https://bugs.chromium.org/p/chromium/issues/detail?id=158753)
Таким образом, если я добавлю к изображению в попапе свойство `image-orientation` - это вызовет неконсистентное поведение между разными браузерами. Не уверена, стоит ли оно того.
